### ISSUE TITLE
Command to list dongers categories

### ISSUE THREAD

**Issue by ameswarb** [frdmn/alfred-dongers#9]
It'd be nice to be able to get a list of the available dongers categories. Selecting an item on the list could call `dongers <category>`

**Comment by frdmn** [comment]
Hehe, this workflow had exactly the both features you are requesting just some months ago. I basically was tired using the categories and got rid of it since I like the builtin alfred sorting mechanism that makes sure the recent items are always at the very top.

Perhaps we can bring back the categories while also somehow allow access to the recently used dongers.

**Comment by ameswarb** [comment]
Could we get a command dedicated to this? i.e. `dongers list cats` (`dongers list` implicitly lists emotes) or `dongers catlist`?

**Comment by frdmn** [comment]
I was thinking about something like this:

| Command | Description |
| --- | --- |
| `dongers` | returns a list of all dongers, starting with the recently used ones at the top |
| `dongers <category>` | returns only dongers from `<category>` |
| `dongers list` | returns a list of available categories. |

What do you think?

**Comment by ameswarb** [comment]
I dig it. 👍

**Comment by frdmn** [comment]
Well then... let's implement it back again! 😁

**Comment by frdmn** [comment]
@ameswarb The [latest version](http://www.packal.org/workflow/dongers) should do this:

![bildschirmfoto 2016-05-27 um 10 35 50](https://cloud.githubusercontent.com/assets/944459/15602656/db126a64-23f6-11e6-8b45-b71fdb303b87.png)

![bildschirmfoto 2016-05-27 um 10 35 55](https://cloud.githubusercontent.com/assets/944459/15602659/dd516348-23f6-11e6-894e-0629f4e5ee8a.png)
